repos:
- repo: https:
rev: v0.11.2
hooks:
- id: ruff
- id: ruff-format
- repo: https:
rev: v5.0.0
hooks:
- id: check-merge-conflict
- id: debug-statements
- id: fix-byte-order-marker
- id: trailing-whitespace
- id: end-of-file-fixer