version: '3'
services:
  combined-approach-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env  
    environment:
      - PROCESSING_SERVICE_URL=http://clone-and-process-service:8000
    depends_on:
      - clone-and-process-service
    volumes:
      - ./app:/app/app
      - ./vector_store:/app/vector_store

  clone-and-process-service:
    build:
      context: ../microservice-clone-and-process
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    volumes:
      - ../microservice-clone-and-process/app:/app/app
      - ../microservice-clone-and-process/repositories:/app/repositories
      - ../microservice-clone-and-process/vector_store:/app/vector_store